spring:
  application:
    name: turnstile-api
  datasource:
    url: jdbc:postgresql://localhost:5432/database
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret:
    wow-secret-wow
  access:
    expiration:
      seconds:
        900
  refresh:
    expiration:
      days:
        1